Fix `make check` with newer versions of clang.
`make check` with Apple clang version 11.0.0 (clang-1100.0.33.16) fails with the following:

```
$ make check
Making check in src
Making check in .
g++ -DHAVE_CONFIG_H -I. -I..   -g -O0 -I.. -std=c++11 -Qunused-arguments -O0 -g -Wall -Werror -DDEBUG -MT cpp_test-cpp_test.o -MD -MP -MF .deps/cpp_test-cpp_test.Tpo -c -o cpp_test-cpp_test.o `test -f 'cpp_test.cpp' || echo './'`cpp_test.cpp
cpp_test.cpp:126:34: error: lambda capture 'j' is not used [-Werror,-Wunused-lambda-capture]
    s.add_method("test12", "i", [j](const lo::Message m)
                                 ^
1 error generated.
make[2]: *** [cpp_test-cpp_test.o] Error 1
make[1]: *** [check-recursive] Error 1
make: *** [check-recursive] Error 1
```

I tried changing this in `src/Makefile.am`:

```
cpp_test_CXXFLAGS = -I$(top_srcdir)
```

to

```
cpp_test_CXXFLAGS = -I$(top_srcdir) -Wunused-lambda-capture
```

But `-Werror` from `CXXFLAGS` overrides `cpp_test_CXXFLAGS` in the generated Makefile because of the generated order of arguments:

```
cpp_test-cpp_test.o: cpp_test.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(cpp_test_CXXFLAGS) $(CXXFLAGS) -MT cpp_test-cpp_test.o -MD -MP -MF $(DEPDIR)/cpp_test-cpp_test.Tpo -c -o cpp_test-cpp_test.o `test -f 'cpp_test.cpp' || echo '$(srcdir)/'`cpp_test.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/cpp_test-cpp_test.Tpo $(DEPDIR)/cpp_test-cpp_test.Po
```

So, I think implementing this as a clang-specific pragma makes sense. If there is a way to do this in Makefile.am rather than in the source file I would love to know how.